[package]
name = "bevy-next-animation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14" }
uuid = { version = "1.9" }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

thiserror = { version = "1.0" }
